spring:
  datasource:
    url: jdbc:mysql:///vodka?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# 自定义配置
vodka:
  plugins:
    sql:
      record:
        enable: true
      page:
        enable: true
